version: "3.7"

networks:
  docker_omicron-base-net:
    external: true

volumes:
  omicron-influxdb-volume:
  omicron-grafana-volume:

services:
  influxdb:
    image: influxdb:1.8.5
    container_name: omicron-influxdb
    restart: on-failure
    environment:
      INFLUXDB_DB: ${OR_INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${OR_INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${OR_INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_HTTP_AUTH_ENABLED: ${OR_INFLUXDB_HTTP_AUTH_ENABLED}
    networks:
      - docker_omicron-base-net
    ports:
      - ${OR_INFLUXDB_PORT}:${OR_INFLUXDB_PORT}
    volumes:
      - omicron-influxdb-volume:/var/lib/influxdb

  influxdb-writer:
    image: mainflux/influxdb-writer:${OR_RELEASE_TAG}
    container_name: omicron-influxdb-writer
    depends_on:
      - influxdb
    restart: on-failure
    environment:
      MF_INFLUX_WRITER_LOG_LEVEL: debug
      MF_BROKER_URL: ${OR_BROKER_URL}
      MF_INFLUX_WRITER_PORT: ${OR_INFLUX_WRITER_PORT}
      MF_INFLUX_WRITER_BATCH_SIZE: ${OR_INFLUX_WRITER_BATCH_SIZE}
      MF_INFLUX_WRITER_BATCH_TIMEOUT: ${OR_INFLUX_WRITER_BATCH_TIMEOUT}
      MF_INFLUXDB_DB: ${OR_INFLUXDB_DB}
      MF_INFLUXDB_HOST: omicron-influxdb
      MF_INFLUXDB_PORT: ${OR_INFLUXDB_PORT}
      MF_INFLUXDB_ADMIN_USER: ${OR_INFLUXDB_ADMIN_USER}
      MF_INFLUXDB_ADMIN_PASSWORD: ${OR_INFLUXDB_ADMIN_PASSWORD}
    ports:
      - ${OR_INFLUX_WRITER_PORT}:${OR_INFLUX_WRITER_PORT}
    networks:
      - docker_omicron-base-net
    volumes:
      - ./config.toml:/config.toml

  grafana:
    image: grafana/grafana:7.3.7
    container_name: omicron-grafana
    depends_on:
      - influxdb
    restart: on-failure
    ports:
      - ${OR_INFLUX_WRITER_GRAFANA_PORT}:${OR_GRAFANA_PORT}
    networks:
      - docker_omicron-base-net
    volumes:
      - omicron-grafana-volume:/var/lib/grafana
