name: CI

on: [push, pull_request]

jobs:
  Ubuntu:
    name: Build on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update
      - name: Build handmotion
        run: cd handmotion && platformio run
      - name: Build wificlient
        run: cd mobileplatform/wificlient && platformio run
      # - name: Build mainmcu
      #   run: cd mobileplatform/mainmcu && platformio run

  Windows:
    name: Build on windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"    
      - name: Activate msys2 & mingw64
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH
      - name: Install deps
        run: |
          pacman --noconfirm -S --needed mingw-w64-x86_64-SDL2
          gcc --version

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update
      - name: Build handmotion
        run: cd handmotion && platformio run
      - name: Build wificlient
        run: cd mobileplatform/wificlient && platformio run
      # - name: Build mainmcu
      #   run: cd mobileplatform/mainmcu && platformio run
